// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/fenr1s/back-end-take-home/domain/models"

// Airliner is an autogenerated mock type for the Airliner type
type Airliner struct {
	mock.Mock
}

// GetAirlines provides a mock function with given fields:
func (_m *Airliner) GetAirlines() ([]*models.Airline, error) {
	ret := _m.Called()

	var r0 []*models.Airline
	if rf, ok := ret.Get(0).(func() []*models.Airline); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Airline)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
