// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"

import mock "github.com/stretchr/testify/mock"

// Flighter is an autogenerated mock type for the Flighter type
type Flighter struct {
	mock.Mock
}

// Search provides a mock function with given fields: c
func (_m *Flighter) Search(c *gin.Context) {
	_m.Called(c)
}
