package api

import (
	"github.com/fenr1s/back-end-take-home/config"
	_ "github.com/fenr1s/back-end-take-home/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/fenr1s/back-end-take-home/interfaces"
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

//Server http server using gin lib
type Server struct {
	FlightController interfaces.Flighter
}

//Run it setup routes for the http server and run on a given port
func (s *Server) Run() {
	r := s.SetupRoutes()
	r.Run(":" + config.APP_PORT)
}

//SetupRoutes it setup routes for the server starting by the api group
func (s *Server) SetupRoutes() *gin.Engine {
	router := gin.Default()
	api := router.Group("/api")
	{
		api.GET("/routes", s.FlightController.Search)
	}

	swagCfg := &ginSwagger.Config{
		URL: "http://localhost:" + config.APP_PORT + "/swagger/doc.json", //The url pointing to API definition
	}

	// use ginSwagger middleware to
	router.GET("/swagger/*any", ginSwagger.CustomWrapHandler(swagCfg, swaggerFiles.Handler))

	return router
}
